services:
  yt-abs:
    build: .
    container_name: yt-abs
    user: "1000:1000"   # UID:GID
    volumes:
      - .:/app:delegated
      - ./config.yml:/app/config.yml:ro
      - ./audiobookshelf:/audiobookshelf:rw
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

