services:
  yt-abs:
    build: .
    container_name: yt-abs
    volumes:
      - .:/app:delegated
      - ./config.yml:/app/config.yml:ro
      - ./audiobookshelf:/audiobookshelf:rw
    environment:
      - PYTHONUNBUFFERED=1

